export enum PositionCode {
  CHU_TICH = 'CHU_TICH',
  PHO_CHU_TICH = 'PHO_CHU_TICH',
  GIAM_DOC = 'GIAM_DOC',
  PHO_GIAM_DOC = 'PHO_GIAM_DOC',
  TRUONG_PHONG = 'TRUONG_PHONG',
  PHO_TRUONG_PHONG = 'PHO_TRUONG_PHONG',
  THU_KY = 'THU_KY',
  CHUYEN_VIEN = 'CHUYEN_VIEN'
}
