spring:
    config:
        import:
            - optional:file:.env[.properties]
            - optional:file:../.env[.properties]
    devtools:
        restart:
            enabled: false
    application:
        name: paperless_meeting
    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update # none | validate | update | create | create-drop
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: false
        defer-datasource-initialization: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect
                type:
                    preferred_uuid_jdbc_type: CHAR

    sql:
        init:
            mode: never

        # giữ nguyên tên bảng và cột theo entity
        # nếu ko có mục này Hibernate sẽ tự đổi tên (vd: userName -> user_name)
    output:
        ansi:
            enabled: always
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 20MB
    # RabbitMQ Configuration
    rabbitmq:
        host: ${SPRING_RABBITMQ_HOST}
        port: ${SPRING_RABBITMQ_PORT}
        username: ${SPRING_RABBITMQ_USERNAME}
        password: ${SPRING_RABBITMQ_PASSWORD}
    # Gmail SMTP Configuration
    mail:
        host: ${SPRING_MAIL_HOST:smtp.gmail.com}
        port: ${SPRING_MAIL_PORT:587}
        username: ${SPRING_MAIL_USERNAME}
        password: ${SPRING_MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

server:
    port: ${SERVER_PORT}
    servlet:
        context-path: /PaperlessMeeting
    tomcat:
        max-swallow-size: -1

# cấu hình CORS để cho phép frontend (chạy trên localhost:3000) truy cập vào backend
app:
    urls:
      frontend: ${APP_FRONTEND_URL:http://localhost:3000}
      backend: ${APP_BACKEND_URL:http://localhost:8081/PaperlessMeeting}
    seed:
        enabled: false
    security:
        frontend-origin: "http://localhost:3000"
        cookie-domain: ""
        secure-cookies: false
        access-token-cookie-name: "ACCESS_TOKEN"
        refresh-token-cookie-name: "REFRESH_TOKEN"
        access-token-expiration-seconds: 90000
        refresh-token-expiration-seconds: 604800
        issuer: "paperless-meeting"
        jwt-secret-base64: ${JWT_SECRET_BASE64}


springdoc:
    swagger-ui:
        try-it-out-enabled: true
        persist-authorization: true
        with-credentials: true
# cấu hình cả Spring Boot Actuator để chọn những endpoint nào được phép truy cập qua HTTP
management:
    endpoints:
        web:
            exposure:
                include: health,info
logging:
    level:
        org.springframework.security: DEBUG
        vn.acme.paperless_meeting.service.auth: DEBUG
